# Generated by Django 4.1.5 on 2023-01-09 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_menu_user_is_restaurant_order_user_menu_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='menu_id',
        ),
        migrations.AddField(
            model_name='menu',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
