# Generated by Django 4.1.5 on 2023-01-11 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_user_menu_id_menu_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
